package com.mach.core.util;

public enum EnumValidation {
    FIELDS,
    ERRORMESSAGEMINIMUMAMOUNT,
    ERRORMESSAGEAMOUNTEXCEEDS,
    MESSAGEDONTHAVEANDACCOUNT,
    ISBALANCEPRESENT,
    ERRORMESSAGEPININVALID,
    ACCOUNTBLOCKEDMESSAGE,
    RECOVERACCOUNTOPTION
}
